# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'grpc', '~> 1.74'
gem 'grpc-tools', '~> 1.74'
gem 'pg', '~> 1.6'
gem 'bunny', '~> 2.24'
gem 'sequel', '~> 5.94'
gem 'dry-validation', '~> 1.11', '>= 1.11.1'
gem 'dry-struct', '~> 1.8'
gem 'dry-types', '~> 1.8', '>= 1.8.3'
gem 'concurrent-ruby', '~> 1.3', '>= 1.3.5'
gem 'redis', '~> 5.4', '>= 5.4.1'
gem 'dotenv', '~> 3.1', '>= 3.1.8'
gem 'logger', '~> 1.7'
gem 'json', '~> 2.13', '>= 2.13.1'
gem 'uuid', '~> 2.3', '>= 2.3.9'
gem 'cgi', '~> 0.5.0'

group :development, :test do
    gem 'rspec', '~> 3.13', '>= 3.13.1'
    gem 'factory_bot', '~> 6.5', '>= 6.5.4'
    gem 'database_cleaner-sequel', '~> 2.0', '>= 2.0.2'
    gem 'rubocop', '~> 1.79'
    gem 'pry', '~> 0.15.2'

end