# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: like.proto for package 'like'

require 'grpc'
require_relative 'like_pb'

module Like
  module LikesService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'like.LikesService'

      rpc :LikePost, ::Like::LikePostRequest, ::Like::LikePostResponse
      rpc :UnlikePost, ::Like::UnlikePostRequest, ::Like::UnlikePostResponse
      rpc :GetUserLikes, ::Like::GetUserLikesRequest, ::Like::GetUserLikesResponse
      rpc :GetPostLikes, ::Like::GetPostLikesRequest, ::Like::GetPostLikesResponse
      rpc :IsPostLiked, ::Like::IsPostLikedRequest, ::Like::IsPostLikedResponse
      rpc :GetLikesCount, ::Like::GetLikesCountRequest, ::Like::GetLikesCountResponse
      rpc :HealthCheck, ::Like::HealthCheckRequest, ::Like::HealthCheckResponse
      rpc :UnlikePosts, ::Like::UnlikePostsRequest, ::Like::UnlikePostResponse
    end

    Stub = Service.rpc_stub_class
  end
end
