# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: media.proto for package 'media'

require 'grpc'
require_relative 'media_pb'

module Media
  module MediaService
    # Media Service definition
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'media.MediaService'

      # Get authentication parameters for ImageKit
      rpc :GetUploadAuth, ::Media::GetUploadAuthRequest, ::Media::GetUploadAuthResponse
      # Get file details by file ID
      rpc :GetFileDetails, ::Media::GetFileDetailsRequest, ::Media::GetFileDetailsResponse
      # Get list of files with optional filters
      rpc :GetFiles, ::Media::GetFilesRequest, ::Media::GetFilesResponse
      # Delete a single file
      rpc :DeleteFile, ::Media::DeleteFileRequest, ::Media::DeleteFileResponse
      # Delete multiple files
      rpc :DeleteMultipleFiles, ::Media::DeleteMultipleFilesRequest, ::Media::DeleteMultipleFilesResponse
      # Upload file
      rpc :UploadFile, ::Media::UploadFileRequest, ::Media::UploadFileResponse
      # Update file details
      rpc :UpdateFileDetails, ::Media::UpdateFileDetailsRequest, ::Media::UpdateFileDetailsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
