// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: protos/post.proto

package postpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Img           string                 `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Desc          string                 `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	IsFeatured    bool                   `protobuf:"varint,9,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	Visit         uint32                 `protobuf:"varint,10,opt,name=visit,proto3" json:"visit,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_protos_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Post) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Post) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Post) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *Post) GetVisit() uint32 {
	if x != nil {
		return x.Visit
	}
	return 0
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Img           string                 `protobuf:"bytes,2,opt,name=img,proto3" json:"img,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	IsFeatured    bool                   `protobuf:"varint,8,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_protos_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePostRequest) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreatePostRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreatePostRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_protos_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{2}
}

func (x *PostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *PostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_protos_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{3}
}

func (x *GetPostRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPostBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostBySlugRequest) Reset() {
	*x = GetPostBySlugRequest{}
	mi := &file_protos_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostBySlugRequest) ProtoMessage() {}

func (x *GetPostBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetPostBySlugRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{4}
}

func (x *GetPostBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Img           string                 `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Desc          string                 `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	IsFeatured    bool                   `protobuf:"varint,9,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_protos_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePostRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePostRequest) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdatePostRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdatePostRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_protos_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePostRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeletePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_protos_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeletePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeletePostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint32               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	UserId        []string               `protobuf:"bytes,2,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostsRequest) Reset() {
	*x = DeletePostsRequest{}
	mi := &file_protos_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostsRequest) ProtoMessage() {}

func (x *DeletePostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostsRequest.ProtoReflect.Descriptor instead.
func (*DeletePostsRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePostsRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeletePostsRequest) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

type ListPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_protos_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{9}
}

func (x *ListPostsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPostsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPostsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListPostsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsResponse) Reset() {
	*x = ListPostsResponse{}
	mi := &file_protos_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsResponse) ProtoMessage() {}

func (x *ListPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsResponse.ProtoReflect.Descriptor instead.
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{10}
}

func (x *ListPostsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPostsResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPostsResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPostsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IncrementVisitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementVisitRequest) Reset() {
	*x = IncrementVisitRequest{}
	mi := &file_protos_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementVisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementVisitRequest) ProtoMessage() {}

func (x *IncrementVisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementVisitRequest.ProtoReflect.Descriptor instead.
func (*IncrementVisitRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{11}
}

func (x *IncrementVisitRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFeaturedPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturedPostsRequest) Reset() {
	*x = GetFeaturedPostsRequest{}
	mi := &file_protos_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturedPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturedPostsRequest) ProtoMessage() {}

func (x *GetFeaturedPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturedPostsRequest.ProtoReflect.Descriptor instead.
func (*GetFeaturedPostsRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{12}
}

func (x *GetFeaturedPostsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPostsByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsByCategoryRequest) Reset() {
	*x = GetPostsByCategoryRequest{}
	mi := &file_protos_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByCategoryRequest) ProtoMessage() {}

func (x *GetPostsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetPostsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{13}
}

func (x *GetPostsByCategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetPostsByCategoryRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPostsByCategoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPostsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsByUserRequest) Reset() {
	*x = GetPostsByUserRequest{}
	mi := &file_protos_post_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByUserRequest) ProtoMessage() {}

func (x *GetPostsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetPostsByUserRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{14}
}

func (x *GetPostsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPostsByUserRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPostsByUserRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsRequest) Reset() {
	*x = SearchPostsRequest{}
	mi := &file_protos_post_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsRequest) ProtoMessage() {}

func (x *SearchPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsRequest.ProtoReflect.Descriptor instead.
func (*SearchPostsRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{15}
}

func (x *SearchPostsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPostsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchPostsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CountPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	IsFeatured    bool                   `protobuf:"varint,3,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountPostsRequest) Reset() {
	*x = CountPostsRequest{}
	mi := &file_protos_post_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountPostsRequest) ProtoMessage() {}

func (x *CountPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountPostsRequest.ProtoReflect.Descriptor instead.
func (*CountPostsRequest) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{16}
}

func (x *CountPostsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CountPostsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CountPostsRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

type CountPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountPostsResponse) Reset() {
	*x = CountPostsResponse{}
	mi := &file_protos_post_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountPostsResponse) ProtoMessage() {}

func (x *CountPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountPostsResponse.ProtoReflect.Descriptor instead.
func (*CountPostsResponse) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{17}
}

func (x *CountPostsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CountPostsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CountPostsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_post_proto protoreflect.FileDescriptor

const file_protos_post_proto_rawDesc = "" +
	"\n" +
	"\x11protos/post.proto\x12\x04post\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x02\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03img\x18\x03 \x01(\tR\x03img\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1f\n" +
	"\vis_featured\x18\t \x01(\bR\n" +
	"isFeatured\x12\x14\n" +
	"\x05visit\x18\n" +
	" \x01(\rR\x05visit\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd3\x01\n" +
	"\x11CreatePostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03img\x18\x02 \x01(\tR\x03img\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1f\n" +
	"\vis_featured\x18\b \x01(\bR\n" +
	"isFeatured\"b\n" +
	"\fPostResponse\x12\x1e\n" +
	"\x04post\x18\x01 \x01(\v2\n" +
	".post.PostR\x04post\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\" \n" +
	"\x0eGetPostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"*\n" +
	"\x14GetPostBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\xe3\x01\n" +
	"\x11UpdatePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03img\x18\x03 \x01(\tR\x03img\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1f\n" +
	"\vis_featured\x18\t \x01(\bR\n" +
	"isFeatured\"<\n" +
	"\x11DeletePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x12DeletePostResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"?\n" +
	"\x12DeletePostsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\rR\x03ids\x12\x17\n" +
	"\auser_id\x18\x02 \x03(\tR\x06userId\"q\n" +
	"\x10ListPostsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\x8f\x01\n" +
	"\x11ListPostsResponse\x12 \n" +
	"\x05posts\x18\x01 \x03(\v2\n" +
	".post.PostR\x05posts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"'\n" +
	"\x15IncrementVisitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"/\n" +
	"\x17GetFeaturedPostsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"a\n" +
	"\x19GetPostsByCategoryRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"Z\n" +
	"\x15GetPostsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"T\n" +
	"\x12SearchPostsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"i\n" +
	"\x11CountPostsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1f\n" +
	"\vis_featured\x18\x03 \x01(\bR\n" +
	"isFeatured\"^\n" +
	"\x12CountPostsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xe5\x06\n" +
	"\vPostService\x129\n" +
	"\n" +
	"CreatePost\x12\x17.post.CreatePostRequest\x1a\x12.post.PostResponse\x123\n" +
	"\aGetPost\x12\x14.post.GetPostRequest\x1a\x12.post.PostResponse\x12?\n" +
	"\rGetPostBySlug\x12\x1a.post.GetPostBySlugRequest\x1a\x12.post.PostResponse\x129\n" +
	"\n" +
	"UpdatePost\x12\x17.post.UpdatePostRequest\x1a\x12.post.PostResponse\x12?\n" +
	"\n" +
	"DeletePost\x12\x17.post.DeletePostRequest\x1a\x18.post.DeletePostResponse\x12<\n" +
	"\tListPosts\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponse\x12A\n" +
	"\x0eIncrementVisit\x12\x1b.post.IncrementVisitRequest\x1a\x12.post.PostResponse\x12J\n" +
	"\x10GetFeaturedPosts\x12\x1d.post.GetFeaturedPostsRequest\x1a\x17.post.ListPostsResponse\x12N\n" +
	"\x12GetPostsByCategory\x12\x1f.post.GetPostsByCategoryRequest\x1a\x17.post.ListPostsResponse\x12F\n" +
	"\x0eGetPostsByUser\x12\x1b.post.GetPostsByUserRequest\x1a\x17.post.ListPostsResponse\x12@\n" +
	"\vSearchPosts\x12\x18.post.SearchPostsRequest\x1a\x17.post.ListPostsResponse\x12?\n" +
	"\n" +
	"CountPosts\x12\x17.post.CountPostsRequest\x1a\x18.post.CountPostsResponse\x12A\n" +
	"\vDeletePosts\x12\x18.post.DeletePostsRequest\x1a\x18.post.DeletePostResponseB\x0fZ\rprotos/postpbb\x06proto3"

var (
	file_protos_post_proto_rawDescOnce sync.Once
	file_protos_post_proto_rawDescData []byte
)

func file_protos_post_proto_rawDescGZIP() []byte {
	file_protos_post_proto_rawDescOnce.Do(func() {
		file_protos_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_post_proto_rawDesc), len(file_protos_post_proto_rawDesc)))
	})
	return file_protos_post_proto_rawDescData
}

var file_protos_post_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_protos_post_proto_goTypes = []any{
	(*Post)(nil),                      // 0: post.Post
	(*CreatePostRequest)(nil),         // 1: post.CreatePostRequest
	(*PostResponse)(nil),              // 2: post.PostResponse
	(*GetPostRequest)(nil),            // 3: post.GetPostRequest
	(*GetPostBySlugRequest)(nil),      // 4: post.GetPostBySlugRequest
	(*UpdatePostRequest)(nil),         // 5: post.UpdatePostRequest
	(*DeletePostRequest)(nil),         // 6: post.DeletePostRequest
	(*DeletePostResponse)(nil),        // 7: post.DeletePostResponse
	(*DeletePostsRequest)(nil),        // 8: post.DeletePostsRequest
	(*ListPostsRequest)(nil),          // 9: post.ListPostsRequest
	(*ListPostsResponse)(nil),         // 10: post.ListPostsResponse
	(*IncrementVisitRequest)(nil),     // 11: post.IncrementVisitRequest
	(*GetFeaturedPostsRequest)(nil),   // 12: post.GetFeaturedPostsRequest
	(*GetPostsByCategoryRequest)(nil), // 13: post.GetPostsByCategoryRequest
	(*GetPostsByUserRequest)(nil),     // 14: post.GetPostsByUserRequest
	(*SearchPostsRequest)(nil),        // 15: post.SearchPostsRequest
	(*CountPostsRequest)(nil),         // 16: post.CountPostsRequest
	(*CountPostsResponse)(nil),        // 17: post.CountPostsResponse
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
}
var file_protos_post_proto_depIdxs = []int32{
	18, // 0: post.Post.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: post.Post.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: post.PostResponse.post:type_name -> post.Post
	0,  // 3: post.ListPostsResponse.posts:type_name -> post.Post
	1,  // 4: post.PostService.CreatePost:input_type -> post.CreatePostRequest
	3,  // 5: post.PostService.GetPost:input_type -> post.GetPostRequest
	4,  // 6: post.PostService.GetPostBySlug:input_type -> post.GetPostBySlugRequest
	5,  // 7: post.PostService.UpdatePost:input_type -> post.UpdatePostRequest
	6,  // 8: post.PostService.DeletePost:input_type -> post.DeletePostRequest
	9,  // 9: post.PostService.ListPosts:input_type -> post.ListPostsRequest
	11, // 10: post.PostService.IncrementVisit:input_type -> post.IncrementVisitRequest
	12, // 11: post.PostService.GetFeaturedPosts:input_type -> post.GetFeaturedPostsRequest
	13, // 12: post.PostService.GetPostsByCategory:input_type -> post.GetPostsByCategoryRequest
	14, // 13: post.PostService.GetPostsByUser:input_type -> post.GetPostsByUserRequest
	15, // 14: post.PostService.SearchPosts:input_type -> post.SearchPostsRequest
	16, // 15: post.PostService.CountPosts:input_type -> post.CountPostsRequest
	8,  // 16: post.PostService.DeletePosts:input_type -> post.DeletePostsRequest
	2,  // 17: post.PostService.CreatePost:output_type -> post.PostResponse
	2,  // 18: post.PostService.GetPost:output_type -> post.PostResponse
	2,  // 19: post.PostService.GetPostBySlug:output_type -> post.PostResponse
	2,  // 20: post.PostService.UpdatePost:output_type -> post.PostResponse
	7,  // 21: post.PostService.DeletePost:output_type -> post.DeletePostResponse
	10, // 22: post.PostService.ListPosts:output_type -> post.ListPostsResponse
	2,  // 23: post.PostService.IncrementVisit:output_type -> post.PostResponse
	10, // 24: post.PostService.GetFeaturedPosts:output_type -> post.ListPostsResponse
	10, // 25: post.PostService.GetPostsByCategory:output_type -> post.ListPostsResponse
	10, // 26: post.PostService.GetPostsByUser:output_type -> post.ListPostsResponse
	10, // 27: post.PostService.SearchPosts:output_type -> post.ListPostsResponse
	17, // 28: post.PostService.CountPosts:output_type -> post.CountPostsResponse
	7,  // 29: post.PostService.DeletePosts:output_type -> post.DeletePostResponse
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_post_proto_init() }
func file_protos_post_proto_init() {
	if File_protos_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_post_proto_rawDesc), len(file_protos_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_post_proto_goTypes,
		DependencyIndexes: file_protos_post_proto_depIdxs,
		MessageInfos:      file_protos_post_proto_msgTypes,
	}.Build()
	File_protos_post_proto = out.File
	file_protos_post_proto_goTypes = nil
	file_protos_post_proto_depIdxs = nil
}
