# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: event.proto for package 'event'

require 'grpc'
require_relative 'event_pb'

module Event
  module EventService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'event.EventService'

      rpc :PublishEvent, ::Event::PublishEventRequest, ::Event::PublishEventResponse
      rpc :GetEvents, ::Event::GetEventsRequest, ::Event::GetEventsResponse
      rpc :GetEventsByAggregate, ::Event::GetEventsByAggregateRequest, ::Event::GetEventsResponse
      rpc :SubscribeToEvents, ::Event::SubscribeToEventsRequest, ::Event::SubscribeToEventsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
