# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'user'

require 'grpc'
require_relative 'user_pb'

module User
  module UserService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'user.UserService'

      rpc :ListUsers, ::User::ListUsersRequest, ::User::ListUsersResponse
      rpc :GetUser, ::User::GetUserRequest, ::User::GetUserResponse
      rpc :GetLocalUser, ::User::GetUserRequest, ::User::GetUserResponse
      rpc :CreateUser, ::User::CreateUserRequest, ::User::CreateUserResponse
      rpc :UpdateUser, ::User::UpdateUserRequest, ::User::UpdateUserResponse
      rpc :DeleteUser, ::User::DeleteUserRequest, ::User::DeleteUserResponse
      rpc :GetUserCount, ::User::UserFilterRequest, ::User::UserCountResponse
      rpc :UpdateUserRole, ::User::UpdateUserRoleRequest, ::User::UpdateUserRoleResponse
      rpc :GetOAuthAccessToken, ::User::OAuthTokenRequest, ::User::OAuthTokenResponse
    end

    Stub = Service.rpc_stub_class
  end
end
