# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: comment.proto for package 'comment'

require 'grpc'
require 'comment_pb'

module Comment
  module CommentService
    # Comment Service
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'comment.CommentService'

      rpc :CreateComment, ::Comment::CreateCommentRequest, ::Comment::CommentResponse
      rpc :GetComment, ::Comment::GetCommentRequest, ::Comment::CommentResponse
      rpc :GetCommentsByPost, ::Comment::GetCommentsByPostRequest, ::Comment::GetCommentsResponse
      rpc :GetCommentsByUser, ::Comment::GetCommentsByUserRequest, ::Comment::GetCommentsResponse
      rpc :UpdateComment, ::Comment::UpdateCommentRequest, ::Comment::CommentResponse
      rpc :DeleteComment, ::Comment::DeleteCommentRequest, ::Comment::DeleteCommentResponse
      rpc :GetCommentCount, ::Comment::GetCommentCountRequest, ::Comment::GetCommentCountResponse
      rpc :DeleteComments, ::Comment::DeleteCommentsRequest, ::Comment::DeleteCommentResponse
    end

    Stub = Service.rpc_stub_class
  end
end
