# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: post.proto for package 'post'

require 'grpc'
require_relative 'post_pb'

module Post
  module PostService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'post.PostService'

      rpc :CreatePost, ::Post::CreatePostRequest, ::Post::PostResponse
      rpc :GetPost, ::Post::GetPostRequest, ::Post::PostResponse
      rpc :GetPostBySlug, ::Post::GetPostBySlugRequest, ::Post::PostResponse
      rpc :UpdatePost, ::Post::UpdatePostRequest, ::Post::PostResponse
      rpc :DeletePost, ::Post::DeletePostRequest, ::Post::DeletePostResponse
      rpc :ListPosts, ::Post::ListPostsRequest, ::Post::ListPostsResponse
      rpc :IncrementVisit, ::Post::IncrementVisitRequest, ::Post::PostResponse
      rpc :GetFeaturedPosts, ::Post::GetFeaturedPostsRequest, ::Post::ListPostsResponse
      rpc :GetPostsByCategory, ::Post::GetPostsByCategoryRequest, ::Post::ListPostsResponse
      rpc :GetPostsByUser, ::Post::GetPostsByUserRequest, ::Post::ListPostsResponse
      rpc :SearchPosts, ::Post::SearchPostsRequest, ::Post::ListPostsResponse
      rpc :CountPosts, ::Post::CountPostsRequest, ::Post::CountPostsResponse
      rpc :DeletePosts, ::Post::DeletePostsRequest, ::Post::DeletePostResponse
    end

    Stub = Service.rpc_stub_class
  end
end
